from django.urls import path

from .views import (
    automation_ai_view,
    automation_rules_view,
    attendants_view,
    change_initial_password_view,
    conversation_list_view,
    conversation_messages_view,
    conversation_name_contact_view,
    conversation_send_media_view,
    conversation_send_view,
    conversation_sync_groups_view,
    conversation_transfer_view,
    conversations_view,
    dashboard_view,
    login_view,
    logout_view,
    password_recovery_request_view,
    password_recovery_resend_view,
    password_recovery_set_password_view,
    password_recovery_verify_code_view,
    sectors_save_organization_view,
    sectors_view,
    wapi_webhook_events_view,
    wapi_webhook_view,
    wapi_settings_view,
)

urlpatterns = [
    path('', login_view, name='login'),
    path('recuperar-senha/solicitar/', password_recovery_request_view, name='password-recovery-request'),
    path('recuperar-senha/reenviar/', password_recovery_resend_view, name='password-recovery-resend'),
    path('recuperar-senha/verificar/', password_recovery_verify_code_view, name='password-recovery-verify'),
    path('recuperar-senha/nova-senha/', password_recovery_set_password_view, name='password-recovery-set-password'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('conversas/', conversations_view, name='conversations'),
    path('conversas/lista/', conversation_list_view, name='conversation-list'),
    path('conversas/sincronizar-grupos/', conversation_sync_groups_view, name='conversation-sync-groups'),
    path('conversas/nomear-contato/', conversation_name_contact_view, name='conversation-name-contact'),
    path('conversas/<int:conversation_id>/mensagens/', conversation_messages_view, name='conversation-messages'),
    path('conversas/<int:conversation_id>/enviar/', conversation_send_view, name='conversation-send'),
    path('conversas/<int:conversation_id>/enviar-midia/', conversation_send_media_view, name='conversation-send-media'),
    path('conversas/<int:conversation_id>/transferir/', conversation_transfer_view, name='conversation-transfer'),
    path('automacao/ia/', automation_ai_view, name='automation-ai'),
    path('automacao/regras/', automation_rules_view, name='automation-rules'),
    path('setores/', sectors_view, name='sectors'),
    path('setores/salvar/', sectors_save_organization_view, name='sectors-save'),
    path('atendentes/', attendants_view, name='attendants'),
    path('trocar-senha-inicial/', change_initial_password_view, name='change-initial-password'),
    path('configuracoes/wapi/', wapi_settings_view, name='wapi-settings'),
    path('configuracoes/wapi/eventos/', wapi_webhook_events_view, name='wapi-webhook-events'),
    # Endpoint publico do webhook da W-API. Registrado tambem sob /beezap/ para
    # funcionar quando o app e servido atras do prefixo /beezap/ no Nginx.
    path('webhook/wapi/', wapi_webhook_view, name='wapi-webhook'),
    path('beezap/webhook/wapi/', wapi_webhook_view, name='wapi-webhook-beezap'),
    path('logout/', logout_view, name='logout'),
]
