# Generated by Django 5.2.12 on 2026-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_attendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
