# Generated by Django 5.2.12 on 2026-07-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo da regra')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('customer_example', models.TextField(blank=True, default='', verbose_name='Pergunta/exemplo do cliente')),
                ('response_text', models.TextField(verbose_name='Resposta orientada')),
                ('internal_instruction', models.TextField(blank=True, default='', verbose_name='Instrucao interna')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='accounts.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Regra de atendimento',
                'verbose_name_plural': 'Regras de atendimento',
                'ordering': ('-is_active', 'title'),
            },
        ),
    ]
