# Generated by Django 5.2.12 on 2026-07-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_default_automation_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='WapiWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='unknown', max_length=80)),
                ('instance_id', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('message_id', models.CharField(blank=True, default='', max_length=160)),
                ('message_type', models.CharField(default='unknown', max_length=60)),
                ('message_text', models.TextField(blank=True, default='')),
                ('from_me', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Evento webhook W-API',
                'verbose_name_plural': 'Eventos webhook W-API',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddField(
            model_name='wapiconfiguration',
            name='webhook_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
