# Generated by Django 6.0.6 on 2026-07-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_contact_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_mimetype',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='message',
            name='media_status',
            field=models.CharField(choices=[('none', 'Sem midia'), ('pending', 'Baixando'), ('ok', 'Disponivel'), ('unavailable', 'Indisponivel')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('gif', 'GIF'), ('reaction', 'Reacao'), ('location', 'Localizacao'), ('contact', 'Contato'), ('unknown', 'Nao suportado')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
