# Generated by Django 6.0.6 on 2026-07-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message_media_file_message_media_mimetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Direta'), ('group', 'Grupo')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='from_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='participant_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.contact'),
        ),
    ]
