# Generated by Django 5.2.12 on 2026-07-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_backfill_conversation_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_state',
            field=models.CharField(choices=[('active', 'IA atendendo'), ('handed_off', 'Transferida pela IA'), ('off', 'IA desligada')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_turns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AiAttendantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Atendente virtual ativo')),
                ('company_name', models.CharField(default='BEEZAP', max_length=120, verbose_name='Nome da empresa')),
                ('welcome_message', models.TextField(default='Ola! Bem-vindo(a) a {empresa}. Sou o atendimento inicial e vou te direcionar para a area certa. Como posso ajudar voce hoje?', help_text='Use {empresa} para inserir o nome da empresa automaticamente.', verbose_name='Mensagem de boas-vindas')),
                ('max_turns', models.PositiveSmallIntegerField(default=3, help_text='Quantas vezes a IA tenta entender antes de transferir mesmo assim.', verbose_name='Tentativas de esclarecer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_fallback_configs', to='accounts.sector', verbose_name='Setor padrao (fallback)')),
            ],
            options={
                'verbose_name': 'Configuracao do atendente virtual',
                'verbose_name_plural': 'Configuracao do atendente virtual',
            },
        ),
    ]
