# Generated by Django 5.2.12 on 2026-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_conversation_ai_state_conversation_ai_turns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiattendantconfig',
            name='llm_only',
            field=models.BooleanField(default=False, help_text='Modo de teste: ignora as regras de palavras-chave e deixa o modelo decidir o setor.', verbose_name='IA decide sozinha (sem palavras-chave)'),
        ),
    ]
