# Generated by Django 5.2.12 on 2026-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_aiattendantconfig_llm_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiattendantconfig',
            name='instructions',
            field=models.TextField(default='Voce e o atendimento inicial da empresa {empresa} no WhatsApp.\nSua funcao e entender o que o cliente precisa e encaminha-lo ao setor certo.\nAnalise a mensagem do cliente e escolha o setor mais adequado entre os disponiveis.\nSeja educado, cordial e objetivo. Use portugues do Brasil.\nNao invente precos, prazos, politicas ou informacoes que voce nao tem.\nNao peca dados sensiveis (senha, cartao, documentos).\nSe a mensagem nao deixar claro o assunto, responda INDEFINIDO para pedir mais detalhes.', help_text='Orienta como a IA escolhe o setor. Use {empresa} para inserir o nome da empresa.', verbose_name='Instrucoes da IA (como decidir o setor)'),
        ),
    ]
