# Generated by Django 5.2.12 on 2026-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_aiattendantconfig_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiattendantconfig',
            name='generative_replies',
            field=models.BooleanField(default=False, help_text='Em vez de mensagens prontas, a IA gera as respostas ao cliente a partir das instrucoes.', verbose_name='IA escreve as respostas (conversa livre)'),
        ),
        migrations.AlterField(
            model_name='aiattendantconfig',
            name='instructions',
            field=models.TextField(default='Voce e um atendente virtual da empresa {empresa}.\nSua funcao e conversar com o cliente de forma educada, paciente e objetiva, entender a necessidade dele e direcionar o atendimento para o setor correto.\nAnalise a mensagem do cliente e verifique qual setor mais combina com o assunto.\n\nRegras obrigatorias:\n- Seja sempre educado, respeitoso, paciente e profissional.\n- Nao invente precos, prazos, condicoes, promocoes, servicos ou informacoes que nao estejam definidos.\n- Nao confirme nada que voce nao tenha certeza. Nao prometa atendimento imediato, desconto, aprovacao ou entrega.\n- Nao tente resolver o assunto: sua funcao e apenas entender e direcionar.\n- Se o cliente perguntar algo que voce nao sabe, ou o assunto nao estiver claro, direcione para o Setor Geral.\n- Se a mensagem estiver confusa, peca educadamente para o cliente explicar melhor.\n- Mantenha as respostas curtas, claras e humanas.\n\nQuando identificar o setor, avise que vai encaminhar o atendimento para aquele setor. Quando nao souber, encaminhe para o Setor Geral. Quando precisar de mais informacao, peca para o cliente explicar melhor.', help_text='Prompt que orienta a IA (persona, regras, direcionamento). Use {empresa} para o nome da empresa. Os setores cadastrados sao inseridos automaticamente.', verbose_name='Instrucoes da IA (prompt do atendimento)'),
        ),
    ]
