# Generated by Django 5.2.12 on 2026-07-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aiattendantconfig_generative_replies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrule',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='ai_state',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='ai_turns',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_ai',
        ),
        migrations.DeleteModel(
            name='AiAttendantConfig',
        ),
        migrations.DeleteModel(
            name='AutomationRule',
        ),
    ]
