# Generated by Django 5.2.12 on 2026-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_automationrule_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('gif', 'GIF'), ('reaction', 'Reacao'), ('location', 'Localizacao'), ('contact', 'Contato'), ('unknown', 'Nao suportado'), ('system', 'Sistema')], default='text', max_length=20),
        ),
    ]
