# Generated by Django 6.0.6 on 2026-07-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, default='gpt-4.1-nano', max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao OpenAI (GPT)',
                'verbose_name_plural': 'Configuracoes OpenAI (GPT)',
            },
        ),
    ]
