# Generated by Django 6.0.6 on 2026-07-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_openaiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiconfiguration',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='total_completion_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='total_prompt_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='total_requests',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='total_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='usage_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
