# Generated by Django 6.0.6 on 2026-07-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_openaiconfiguration_last_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_turns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='fallback_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_fallback_configs', to='accounts.sector'),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='max_turns',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
