# Generated by Django 6.0.6 on 2026-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_conversation_ai_turns_message_is_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiconfiguration',
            name='last_exchange_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='last_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='openaiconfiguration',
            name='last_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
