# Generated by Django 5.2.12 on 2026-07-09 17:04

import django.db.models.deletion
from django.db import migrations, models


def set_initial_mode(apps, schema_editor):
    """Preserva o comportamento atual: se a IA (OpenAiConfiguration) ja estava
    ligada, o modo mestre nasce como 'ai'; senao 'off'."""
    OpenAiConfiguration = apps.get_model('accounts', 'OpenAiConfiguration')
    MenuBotConfiguration = apps.get_model('accounts', 'MenuBotConfiguration')
    ai = OpenAiConfiguration.objects.filter(pk=1).first()
    mode = 'ai' if (ai and ai.enabled) else 'off'
    MenuBotConfiguration.objects.update_or_create(pk=1, defaults={'mode': mode})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_openaiconfiguration_last_exchange_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('off', 'Desligado'), ('menu', 'Chatbot de menu'), ('ai', 'Inteligencia (IA)')], default='off', max_length=10)),
                ('greeting', models.TextField(blank=True, default='')),
                ('menu_intro', models.TextField(blank=True, default='')),
                ('invalid_message', models.TextField(blank=True, default='')),
                ('confirmation_message', models.TextField(blank=True, default='')),
                ('handoff_message', models.TextField(blank=True, default='')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menubot_fallback_configs', to='accounts.sector')),
            ],
            options={
                'verbose_name': 'Configuracao do chatbot (menu)',
                'verbose_name_plural': 'Configuracoes do chatbot (menu)',
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.menubotconfiguration')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_options', to='accounts.sector')),
            ],
            options={
                'verbose_name': 'Opcao do menu',
                'verbose_name_plural': 'Opcoes do menu',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RunPython(set_initial_mode, noop),
    ]
