# Generated by Django 5.2.12 on 2026-07-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_backfill_admin_attendants'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, unique=True)),
                ('allowed_keys', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permissao de menu (perfil)',
                'verbose_name_plural': 'Permissoes de menu (perfis)',
            },
        ),
        migrations.CreateModel(
            name='UserMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_keys', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissao de menu (usuario)',
                'verbose_name_plural': 'Permissoes de menu (usuarios)',
            },
        ),
    ]
