# Generated by Django 5.2.12 on 2026-07-09 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rolemenupermission_usermenupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenupermission',
            name='full_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermenupermission',
            name='full_history',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='accounts.conversation')),
                ('sectors', models.ManyToManyField(blank=True, related_name='group_accesses', to='accounts.sector')),
                ('users', models.ManyToManyField(blank=True, related_name='group_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a grupo',
                'verbose_name_plural': 'Acessos a grupos',
            },
        ),
    ]
