# Generated by Django 6.0.6 on 2026-07-15 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_default_general_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='view_full_history',
            field=models.BooleanField(default=False, verbose_name='Ver conversa inteira'),
        ),
        migrations.AddField(
            model_name='sector',
            name='view_scope',
            field=models.CharField(choices=[('own', 'Somente as próprias conversas'), ('sector_open', 'Conversas em aberto do setor'), ('sector_all', 'Todas do setor (inclui finalizadas)'), ('all', 'Conversas de todos os setores')], default='sector_open', max_length=20, verbose_name='Alcance de visualização'),
        ),
        migrations.CreateModel(
            name='UserConversationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_scope', models.CharField(blank=True, choices=[('own', 'Somente as próprias conversas'), ('sector_open', 'Conversas em aberto do setor'), ('sector_all', 'Todas do setor (inclui finalizadas)'), ('all', 'Conversas de todos os setores')], max_length=20, null=True)),
                ('view_full_history', models.BooleanField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_view', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de conversas (usuário)',
                'verbose_name_plural': 'Visualizações de conversas (usuários)',
            },
        ),
    ]
