# Generated by Django 6.0.6 on 2026-07-15 01:18

import django.db.models.deletion
from django.db import migrations, models


# Texto da divisoria que abre um novo atendimento (igual a wapi.services.SYSTEM_NEW_SERVICE_TEXT).
NEW_SERVICE_TEXT = 'Novo atendimento iniciado'


def backfill_current_segment_sector(apps, schema_editor):
    """Backfill do setor nas mensagens do ATENDIMENTO ATUAL (ultimo segmento) de cada
    conversa — que corresponde ao `Conversation.sector` atual (dado confiavel). Os
    atendimentos anteriores (fechados/transferidos) ficam sem setor: nao ha como saber
    o setor historico, e a partir daqui toda mensagem nova ja nasce carimbada."""
    Conversation = apps.get_model('accounts', 'Conversation')
    Message = apps.get_model('accounts', 'Message')
    for conv in Conversation.objects.exclude(sector__isnull=True).iterator():
        last_div = (
            Message.objects
            .filter(conversation=conv, message_type='system', text=NEW_SERVICE_TEXT)
            .order_by('-created_at').first()
        )
        qs = Message.objects.filter(conversation=conv)
        if last_div is not None:
            qs = qs.filter(created_at__gte=last_div.created_at)
        qs.update(sector=conv.sector_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_sector_view_full_history_sector_view_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='accounts.sector'),
        ),
        migrations.RunPython(backfill_current_segment_sector, noop),
    ]
