# Generated by Django 5.2.12 on 2026-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_openai_config_da_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp para recuperar a senha'),
        ),
    ]
