# Generated by Django 5.2.12 on 2026-08-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_gestor_master_recuperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('total_requests', models.PositiveBigIntegerField(default=0)),
                ('total_prompt_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_completion_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='accounts.company', verbose_name='Empresa cliente')),
            ],
            options={
                'verbose_name': 'Consumo de IA da empresa',
                'verbose_name_plural': 'Consumo de IA das empresas',
                'ordering': ('-year', '-month', 'company__name'),
                'constraints': [models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_company_ai_usage_month')],
            },
        ),
    ]
