"""Indices para as consultas quentes (o schema tinha exatamente UM).

Antes desta migration o unico `db_index` declarado no projeto era
`Conversation.external_id`. As chaves estrangeiras ganham indice sozinhas, mas as
consultas reais do sistema sao COMPOSTAS e nenhuma tinha cobertura:

- a tela Conversas roda 8 contadores (5 por status + 3 por tipo) a cada poll de 12
  segundos, todos `company` + algo;
- abrir uma conversa (e o poll de 6 segundos) le as mensagens daquela conversa em
  ordem de data, e o escopo por divisoria filtra `message_type='system'` + data;
- as telas de Metricas contam mensagens por faixa de data sobre a tabela inteira;
- a deduplicacao do webhook busca por `external_message_id` em toda mensagem que
  chega;
- as Metricas dos clientes pedem `Max(received_at)` por empresa em
  `WapiWebhookEvent`, que e a maior tabela do sistema em numero de linhas.

Nada aqui muda comportamento — e a mudanca de melhor retorno por esforco do pente
fino: barata, sem risco e sem tocar em nenhuma view.

Em producao a base ainda e pequena, entao a migration roda em segundos. Vale rodar
com o app no ar sem preocupacao.
"""

# Generated by Django 5.2.12 on 2026-08-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_marca_do_cliente_nos_textos_automaticos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'name'], name='contato_empresa_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'status'], name='conv_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', '-last_message_at'], name='conv_company_ultima_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'chat_type'], name='conv_company_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'created_at'], name='conv_company_criada_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_data_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'message_type', '-created_at'], name='msg_conv_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='msg_data_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_message_id'], name='msg_id_externo_idx'),
        ),
        migrations.AddIndex(
            model_name='wapiwebhookevent',
            index=models.Index(fields=['company', '-received_at'], name='evento_empresa_data_idx'),
        ),
        migrations.AddIndex(
            model_name='wapiwebhookevent',
            index=models.Index(fields=['instance_id'], name='evento_instancia_idx'),
        ),
    ]
