# Generated by Django 5.2.12 on 2026-08-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_indices_das_consultas_quentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_reply_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
