"""Remove seis campos mortos, achados no pente fino do projeto.

Nenhum deles era lido por tela, endpoint, comando ou exportacao. O custo de mante-los
nao era so espaco: cada um e uma pista falsa para quem (ou qual sessao de agente) abrir
o arquivo depois — e dois deles estavam descritos na documentacao como se estivessem em
uso.

- `Message.phone`: era GRAVADO em todos os pontos de criacao de mensagem e nunca lido.
  Numa tabela que cresce com o volume de mensagens, e a coluna morta mais cara.
- `OpenAiConfiguration.enabled`: vestigial desde que o MODO de primeiro atendimento de
  cada empresa (`MenuBotConfiguration.mode`) virou a fonte unica da verdade. Continuava
  sendo escrito a cada troca de modo, sem ninguem ler. Uma flag da plataforma nao
  poderia mesmo decidir por cada cliente.
- `RoleMenuPermission.full_history` e `UserMenuPermission.full_history`: legado. O
  controle de "ver conversa inteira" migrou para a aba Visualizacao de conversas
  (`Sector.view_full_history` / `UserConversationView.view_full_history`).
- `WapiWebhookEvent.processed` e `processing_error`: nunca foram escritos. Por causa
  disso a propriedade `status_label` respondia SEMPRE "Recebido" — ela saiu junto.

Sem perda de informacao: nada aqui alimentava tela nem relatorio.
"""

# Generated by Django 5.2.12 on 2026-08-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_trava_de_atendimento_automatico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='openaiconfiguration',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='rolemenupermission',
            name='full_history',
        ),
        migrations.RemoveField(
            model_name='usermenupermission',
            name='full_history',
        ),
        migrations.RemoveField(
            model_name='wapiwebhookevent',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='wapiwebhookevent',
            name='processing_error',
        ),
    ]
