# Generated by Django 5.2.12 on 2026-08-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_inscricao_de_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='accounts.sector', verbose_name='Setores'),
        ),
        migrations.CreateModel(
            name='ContactSectorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_access', to='accounts.sector', verbose_name='Setor dos contatos')),
                ('sectors', models.ManyToManyField(blank=True, related_name='contact_accesses_granted', to='accounts.sector', verbose_name='Setores liberados')),
                ('users', models.ManyToManyField(blank=True, related_name='contact_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas liberadas')),
            ],
            options={
                'verbose_name': 'Acesso à carteira de contatos',
                'verbose_name_plural': 'Acessos às carteiras de contatos',
            },
        ),
    ]
