# Generated by Django 5.2.12 on 2026-08-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_contatos_por_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_classify_contacts',
            field=models.BooleanField(default=True, verbose_name='Classificar contatos automaticamente'),
        ),
    ]
