"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, urlparse, unquote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on', 'sim')


def env_list(name, default=None):
    value = os.getenv(name, '')
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


# Opcoes do SQLite em uso concorrente.
#
# O sistema tem 2 workers do gunicorn MAIS threads de background (download de midia,
# IA, chatbot) gravando na mesma base. No modo padrao do SQLite, uma escrita bloqueia
# as leituras e o `timeout` de 5s do driver estoura como `database is locked` — e
# estouraria justamente na hora de responder um cliente.
#
#  - journal_mode=WAL: leitura e escrita deixam de se bloquear;
#  - synchronous=NORMAL: seguro com WAL e bem mais rapido que FULL;
#  - timeout=20: espera pela trava em vez de falhar na hora.
#
# Com PostgreSQL (DATABASE_URL) nada disso e necessario.
SQLITE_OPTIONS = {
    'timeout': 20,
    'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
    'transaction_mode': 'IMMEDIATE',
}


def build_database_config():
    database_url = os.getenv('DATABASE_URL', '').strip()
    if not database_url:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': dict(SQLITE_OPTIONS),
        }

    parsed = urlparse(database_url)
    if parsed.scheme in ('sqlite', 'sqlite3'):
        db_path = unquote(parsed.path or '')
        if db_path.startswith('/'):
            db_path = db_path[1:] if os.name == 'nt' and len(db_path) > 2 and db_path[2] == ':' else db_path
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path or BASE_DIR / 'db.sqlite3',
            'OPTIONS': dict(SQLITE_OPTIONS),
        }

    if parsed.scheme in ('postgres', 'postgresql'):
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote((parsed.path or '').lstrip('/')),
            'USER': unquote(parsed.username or ''),
            'PASSWORD': unquote(parsed.password or ''),
            'HOST': parsed.hostname or '',
            'PORT': str(parsed.port or ''),
            'OPTIONS': dict(parse_qsl(parsed.query)),
        }

    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': dict(SQLITE_OPTIONS),
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
CHAVE_DE_DESENVOLVIMENTO = 'django-insecure-local-dev-key-change-me'
SECRET_KEY = os.getenv('SECRET_KEY', CHAVE_DE_DESENVOLVIMENTO)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

# FALHAR ALTO em vez de rodar inseguro em silencio.
#
# Se o EnvironmentFile do systemd nao carregar (arquivo renomeado, permissao errada,
# unit editado), a aplicacao subia normalmente com a chave de desenvolvimento — que
# esta versionada, publica. Com ela, sessao e token assinado ficam FORJAVEIS, e nada
# na tela indicaria o problema. Melhor o servico nao subir.
if not DEBUG and SECRET_KEY == CHAVE_DE_DESENVOLVIMENTO:
    raise RuntimeError(
        'SECRET_KEY nao configurada: com DEBUG=False o sistema nao sobe com a chave '
        'de desenvolvimento (ela e publica, versionada). Defina SECRET_KEY no .env — '
        'ver docs/DEPLOY.md.'
    )

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1', '[::1]'])
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', [])
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# COOKIES COM NOME PROPRIO — nao e detalhe, e um bug ja observavel.
#
# O VPS serve varios sistemas Django no MESMO dominio, cada um sob um prefixo de
# caminho (/beeonboard/, /trade/, /tradeanalise/, /italiano-ti/, ...). Com o nome
# padrao do Django (`sessionid`, `csrftoken`) no caminho `/`, os sistemas SOBRESCREVEM
# a sessao um do outro: entrar num derruba o login do outro. Os vizinhos ja resolveram
# assim (`italianoti_sessionid`, `italiano_sessionid`, `formdesenv_sessionid`).
SESSION_COOKIE_NAME = os.getenv('SESSION_COOKIE_NAME', 'beeonboard_sessionid')
CSRF_COOKIE_NAME = os.getenv('CSRF_COOKIE_NAME', 'beeonboard_csrftoken')
# O cookie tambem fica restrito ao prefixo do app, quando ha prefixo.
SESSION_COOKIE_PATH = os.getenv('SESSION_COOKIE_PATH') or (
    (os.getenv('FORCE_SCRIPT_NAME') or '').rstrip('/') + '/'
)
CSRF_COOKIE_PATH = SESSION_COOKIE_PATH

# Cookie so por HTTPS quando o site esta em producao (o dominio e servido por TLS).
# Em desenvolvimento (DEBUG) fica False, senao o login local pararia de funcionar.
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HSTS: desligado por PADRAO de proposito. Ele vale para o DOMINIO INTEIRO, nao so
# para /beeonboard/, entao ligar aqui afetaria todos os outros sistemas do servidor —
# e um `max-age` alto e dificil de desfazer. Ligar via .env, com decisao consciente.
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
# O redirecionamento para HTTPS e feito pelo Nginx do dominio.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)

# Prefixo de caminho quando o app e servido sob um sub-caminho (ex.: /beeonboard/).
# Com isso, reverse()/{% url %}/redirects geram URLs ja com o prefixo. O Nginx
# do VPS remove o /beeonboard/ antes de repassar (proxy_pass .../), entao a resolucao
# usa o caminho sem prefixo. Local (sem a variavel) fica vazio e nada muda.
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME') or None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.InitialPasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Marca (logo/nome) da empresa cliente de quem esta logado, usada
                # na barra lateral de todas as telas. Ver accounts/context_processors.py.
                'accounts.context_processors.branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {'default': build_database_config()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL pode incluir o prefixo de deploy (ex.: /beeonboard/static/) via variavel
# de ambiente, para NAO precisar editar este arquivo no servidor. Local usa /static/.
STATIC_URL = os.getenv('STATIC_URL', '/static/')

# IMPORTANTE: manter a pasta static/ do projeto aqui. Se este valor ficar vazio ([]),
# o `collectstatic` NAO publica o CSS/JS do projeto e as alteracoes nao aparecem
# em producao (bug ja ocorrido). Ver docs/DEPLOY.md.
STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Como STATIC_URL: pode incluir o prefixo de deploy (ex.: /beeonboard/media/) via env.
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'

# Nomes de rota (nao caminhos fixos) para que herdem o prefixo de FORCE_SCRIPT_NAME.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

WAPI_BASE_URL = os.getenv('WAPI_BASE_URL', 'https://api.w-api.app')
WAPI_INSTANCE_ID = os.getenv('WAPI_INSTANCE_ID', '')
WAPI_TOKEN = os.getenv('WAPI_TOKEN', '')
WAPI_WEBHOOK_TOKEN = os.getenv('WAPI_WEBHOOK_TOKEN', '')

# Tamanho maximo (MB) de arquivo enviado como midia pela conversa (LITE).
WAPI_MEDIA_MAX_MB = int(os.getenv('WAPI_MEDIA_MAX_MB', '16'))

# Integracao com a API do OpenAI (GPT). A API Key fica no BANCO (tela
# Inteligencia (IA)); estas variaveis sao apenas fallback opcional por ambiente.
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', 'https://api.openai.com')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1-nano')
# Timeout (segundos) das chamadas ao GPT.
OPENAI_TIMEOUT = int(os.getenv('OPENAI_TIMEOUT', '30'))

# Logging
# Sem esta config, os logs INFO da aplicacao (beezap.*) nao apareciam no journal
# (o padrao do Django so emite WARNING+ para loggers nao-django). Aqui os logs
# de webhook/envio/midia vao para o stdout/stderr capturado pelo systemd/journald,
# em nivel INFO por padrao (ajustavel via BEEZAP_LOG_LEVEL). Cada log ja evita
# expor token/payload/telefone completo.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'beezap': {'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'beezap',
        },
    },
    'loggers': {
        'beezap': {
            'handlers': ['console'],
            'level': os.getenv('BEEZAP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Runner de testes: usa hash de senha rapido SO durante os testes (a suite cria
# usuario em quase todo teste e o PBKDF2 dominava o tempo). Ver accounts/test_runner.py.
TEST_RUNNER = 'accounts.test_runner.FastPasswordHasherRunner'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
